### ISSUE TITLE
Package.json file is missing in the project.

### ISSUE THREAD

**Issue by Abhishek-465** [1Shubham7/code-buddy#17]
The project cannot be set up locally.It is showing error because Package,json file is missing. Kindly resolve this issue.

**Comment by 1Shubham7** [comment]
Hey @Abhishek-465, We offcourse have a package.json file. Check in the frontend folder.
Would you like to create a section in contribution.md explaining the local development of the front end part?
BTW the package.json file - https://github.com/1Shubham7/code-buddy/blob/main/frontend/package.json

**Comment by Abhishek-465** [comment]
Ok then to locally run the front end part.. I have to write cd frontend then npm i and npm start?

**Comment by 1Shubham7** [comment]
yes, you are right.

**Comment by 1Shubham7** [comment]
shall we close this issue then?

**Comment by Abhishek-465** [comment]
Okay. Thank you @1Shubham7
