### ISSUE TITLE
Add Modern buttons and Suitable font filter section

### ISSUE THREAD

**Issue by AaadityaG** [1Shubham7/code-buddy#43]
This buttons and and their font style is not suitalble for webapp

![Capture](https://github.com/1Shubham7/code-buddy/assets/114663382/65fe1813-9a7d-4b23-a84b-e39ce325bd31)

**Comment by AaadityaG** [comment]
Allow Me to do it...

**Comment by AaadityaG** [comment]
Allow Me to do it!

I am participating in KWoC and Codepeak

**Comment by Thesumitkrsingh** [comment]
I want to work on these as a newbie in open-source

**Comment by AaadityaG** [comment]
I am working on it...
