### ISSUE TITLE
Adding scroll-reveal to improve the UI || Work under KWoC 

### ISSUE THREAD

**Issue by sambitsingha** [1Shubham7/code-buddy#47]
- The scroll reveal , if added will load the elements one affter the other. It can be customised according to time-delay  and directions according the UI.
- I would like to work on it for KWoC

**Comment by 1Shubham7** [comment]
That's a great idea. Assigning it to you.

**Comment by sambitsingha** [comment]
As the issue has been solved, I am closing it as successful.
