### ISSUE TITLE
creating  a privacy policy page in the website

### ISSUE THREAD

**Issue by 1Shubham7** [1Shubham7/code-buddy#9]

**Comment by nikohoffren** [comment]
Do you want this privacy policy as a link to the website or just as privacypolicy.md file?

**Comment by 1Shubham7** [comment]
@nikohoffren if you wish you can create an md file, I will add it to the website. do you want to work on this issue

**Comment by nikohoffren** [comment]
> @nikohoffren if you wish you can create an md file, I will add it to the website. do you want to work on this issue

Okey, yeah i would like to work on this issue.

**Comment by 1Shubham7** [comment]
ok, assigning it to you

**Comment by nikohoffren** [comment]
PRIVACY_POLICY.md added.
